# 📘Домашнє завдання №14 Boosting

Виконав: **Bohdan Pinchuk**

Link: https://github.com/BogdanPinchuk/DataScience-PBY_HW14

# Частина 1. Класифікація

---

## 📌 Завдання 1. Класифікація (Titanic)

Використайте датасет Titanic:  
https://www.kaggle.com/datasets/yasserh/titanic-dataset  

### Необхідно:
- Завантажити дані
- Провести базовий аналіз:
  - розмір датасету
  - типи змінних
  - кількість пропусків
- Обробити пропущені значення
- Видалити неінформативні колонки (наприклад: `Name`, `Ticket`, `Cabin`, якщо вважаєте за потрібне)
- Обробити категоріальні змінні:
  - для **XGBoost** → використати `OneHotEncoding`
  - для **LightGBM** → використати native categorical features
  - для **CatBoost** → використати native categorical features

### Цільова змінна:
`Survived`

---

## 📌 Завдання 2. Побудова моделей класифікації

Побудуйте **три моделі**:

- `XGBClassifier`
- `LGBMClassifier`
- `CatBoostClassifier`

### Для кожної моделі:
- натренуйте модель
- зробіть прогноз
- обчисліть метрики:
  - Accuracy
  - Precision
  - Recall
  - F1-score
  - ROC-AUC

---

### Порівняйте результати моделей

Створіть таблицю такого формату:

| Model | Accuracy | Precision | Recall | F1 | ROC-AUC |
|--------|------------|------------|--------|-----|----------|
| XGBoost | ? | ? | ? | ? | ? |
| LightGBM | ? | ? | ? | ? | ? |
| CatBoost | ? | ? | ? | ? | ? |

---

### Проаналізуйте:
- яка модель показала найкращий результат
- чи достатньо accuracy для задачі Titanic
- яка модель найзручніша в роботі з категоріальними змінними

---

## 📌 Завдання 3. Feature Importance (класифікація)

Для кожної моделі:

- отримайте важливість ознак
- побудуйте графік feature importance

### Проаналізуйте:
- які ознаки найважливіші
- чи співпадає це з інтуїцією:
  - `Sex`
  - `Pclass`
  - `Age`
  - `Fare`

---

# Частина 2. Регресія

---

## 📌 Завдання 4. Регресія (Fish Market)

Використайте датасет Fish Market:  
https://www.kaggle.com/datasets/vipullrathod/fish-market  

### Цільова змінна:
`Weight`

---

### Попередня обробка:
- дослідити дані
- перевірити пропуски
- обробити категоріальну змінну `Species`

### Для моделей:
- **XGBoost** → OneHotEncoding
- **LightGBM** → native categorical features
- **CatBoost** → native categorical features

---

## 📌 Завдання 5. Побудова моделей регресії

Побудуйте:

- `XGBRegressor`
- `LGBMRegressor`
- `CatBoostRegressor`

### Для кожної моделі:
- натренуйте модель
- зробіть прогноз
- обчисліть метрики:
  - MAE
  - MSE
  - RMSE
  - R²

---

### Порівняйте результати моделей

Створіть таблицю такого формату:

| Model | MAE | MSE | RMSE | R² |
|--------|------|------|------|------|
| XGBoost | ? | ? | ? | ? |
| LightGBM | ? | ? | ? | ? |
| CatBoost | ? | ? | ? | ? |

---

### Проаналізуйте:
- яка модель працює найкраще
- чи вплинула обробка категоріальних змінних на результат
- яка модель найпростіша у використанні

---

## 📌 Завдання 6. Feature Importance (регресія)

Для кожної моделі:

- отримайте feature importance
- побудуйте графіки

### Проаналізуйте:
- які характеристики риби найбільше впливають на вагу:
  - `Length`
  - `Height`
  - `Width`
  - `Species`

In [1]:
# Silent installation or update

package_array = [
    "pip",
    "jinja2",
    "ipywidgets",
    "nbformat",
    "kagglehub[pandas-datasets]",
]

# !python3 -m pip install --upgrade pip -q
for package_name in package_array:
    # !bash -c "echo '{package_name}'"
    !bash -c "python3 -m pip show '{package_name}' > /dev/null 2>&1 || python3 -m pip install --upgrade '{package_name}' -q"

In [2]:
# Synchronization with remote source

import shutil
from pathlib import Path

# Input data
git_project_url = "https://github.com/BogdanPinchuk/DataScience-PBY_HW14.git"
main_file_name = "Bohdan_Pinchuk_DS_HW14.ipynb"

# Solution

# upload all files
current_path = !pwd
current_path = current_path[0]
parent_path = !dirname "$current_path"
parent_path = parent_path[0]
temp_path = f"{parent_path}/temp"

# Clone data
!rm -rf "$temp_path"
!git clone "$git_project_url" "$temp_path"

source = Path(temp_path)
destination = Path(current_path)
exclude = {main_file_name, ".git", ".idea"}

for item in source.iterdir():
    if item.name in exclude:
        continue

    target = destination / item.name
    if item.is_dir():
        shutil.copytree(item, target, dirs_exist_ok=True)
    else:
        shutil.copy2(item, target)

# Clean temp folder
!rm -rf "$temp_path"

Cloning into '/Users/bohdanpinchuk/Documents/Data Science/Development/Data_Science/Practical_tasks/Homework_14/temp'...
remote: Enumerating objects: 38, done.
remote: Counting objects: 100% (38/38), done.
remote: Compressing objects: 100% (30/30), done.
remote: Total 38 (delta 8), reused 37 (delta 7), pack-reused 0 (from 0)
Receiving objects: 100% (38/38), 48.91 KiB | 794.00 KiB/s, done.
Resolving deltas: 100% (8/8), done.

In [3]:
## Downloading data

import apps.main as mn

# Input data
update_db = False
db_file_name = "resources/store_hw14.db"

# Solution
titanic_dataset = mn.download_and_extract_from_kagglehub("yasserh/titanic-dataset", "Titanic-Dataset.csv",
                                                         db_file_name, update_db)
fish_market = mn.download_and_extract_from_kagglehub("vipullrathod/fish-market", "Fish.csv",
                                                     db_file_name, update_db)

# Print result
# display(titanic_dataset, fish_market)

## ✅ Рішення 1
Використайте датасет Titanic.

Необхідно:
- Завантажити дані
- Провести базовий аналіз:
  - розмір датасету
  - типи змінних
  - кількість пропусків
- Обробити пропущені значення
- Видалити неінформативні колонки (наприклад: `Name`, `Ticket`, `Cabin`, якщо вважаєте за потрібне)
- Обробити категоріальні змінні:
  - для **XGBoost** → використати `OneHotEncoding`
  - для **LightGBM** → використати native categorical features
  - для **CatBoost** → використати native categorical features

Цільова змінна: `Survived`

In [4]:
# Data analysis

import numpy as np
import pandas as pd
import apps.reporter as rpt

# Input data
data_set = titanic_dataset
n_columns = data_set.columns.size
n_rows = data_set.index.size

# Solution
columns_df = pd.DataFrame(data_set.columns, columns=["Columns"])
types_df = pd.DataFrame(data_set.dtypes, columns=["Types"])

col_num_type = data_set.select_dtypes(include=np.number).columns
col_cat_type = data_set.select_dtypes(exclude=np.number).columns

empty_val_by_col = data_set.isnull().sum().to_frame(name='count')
is_empty_val = empty_val_by_col.values.sum() > 0

rp = rpt.Reporter()
rp.add_item("Кількість рядків", str(n_rows))
rp.add_item("Кількість об’єктів у датасеті", str(n_rows))
rp.add_item("Кількість стовпців", str(n_columns))
rp.add_item("Кількість числових ознак", str(col_num_type.size))
rp.add_item("Кількість категоріальних ознак", str(col_cat_type.size))
rp.add_item("Пропущені значення", 'є' if is_empty_val > 0 else 'немає')
rp.print_pd_report("Параметри таблиці до обробки")

if is_empty_val > 0:
    display(empty_val_by_col.style.set_caption("Кількість пропусків"))
display(types_df.style.set_caption("Типи даних"))

# Print results
display(data_set)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [5]:
# Data preparation

import numpy as np
import pandas as pd
import apps.reporter as rpt
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

# Input data
fil_num_col_list = ["Age"]
fil_cat_col_list = ["Embarked"]
cat_col_list = ["Sex"]
pd.options.display.float_format = "{:g}".format

# Solution
preprocessor = ColumnTransformer([
    ("fil_num", SimpleImputer(strategy="median"), fil_num_col_list),
    ("fil_cat", SimpleImputer(strategy="most_frequent"), fil_cat_col_list),
], remainder="passthrough", verbose_feature_names_out=False)

preprocessor.set_output(transform="pandas")
transformed_data = preprocessor.fit_transform(titanic_dataset)
titanic_dataset = pd.DataFrame(transformed_data, columns=preprocessor.get_feature_names_out())

data_set = titanic_dataset
n_columns = data_set.columns.size
n_rows = data_set.index.size

columns_df = pd.DataFrame(data_set.columns, columns=["Columns"])
types_df = pd.DataFrame(data_set.dtypes, columns=["Types"])

col_num_type = data_set.select_dtypes(include=np.number).columns
col_cat_type = data_set.select_dtypes(exclude=np.number).columns

empty_val_by_col = data_set.isnull().sum().to_frame(name='count')
is_empty_val = empty_val_by_col.values.sum() > 0

rp = rpt.Reporter()
rp.add_item("Кількість рядків", str(n_rows))
rp.add_item("Кількість об’єктів у датасеті", str(n_rows))
rp.add_item("Кількість стовпців", str(n_columns))
rp.add_item("Кількість числових ознак", str(col_num_type.size))
rp.add_item("Кількість категоріальних ознак", str(col_cat_type.size))
rp.add_item("Пропущені значення", 'є' if is_empty_val > 0 else 'немає')
rp.print_pd_report("Параметри таблиці без кодування")

# Print results
if is_empty_val > 0:
    display(empty_val_by_col.style.set_caption("Кількість пропусків"))
display(types_df.style.set_caption("Типи даних"))
display(data_set)

,Age,Embarked,PassengerId,Survived,Pclass,Name,Sex,SibSp,Parch,Ticket,Fare,Cabin
0,22,S,1,0,3,"Braund, Mr. Owen Harris",male,1,0,A/5 21171,7.25,NaN
1,38,C,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",female,1,0,PC 17599,71.2833,C85
2,26,S,3,1,3,"Heikkinen, Miss. Laina",female,0,0,STON/O2. 3101282,7.925,NaN
3,35,S,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,1,0,113803,53.1,C123
4,35,S,5,0,3,"Allen, Mr. William Henry",male,0,0,373450,8.05,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
886,27,S,887,0,2,"Montvila, Rev. Juozas",male,0,0,211536,13,NaN
887,19,S,888,1,1,"Graham, Miss. Margaret Edith",female,0,0,112053,30,B42
888,28,S,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,1,2,W./C. 6607,23.45,NaN
889,26,C,890,1,1,"Behr, Mr. Karl Howell",male,0,0,111369,30,C148
890,32,Q,891,0,3,"Dooley, Mr. Patrick",male,0,0,370376,7.75,NaN

In [6]:
# Data preparation

import numpy as np
import pandas as pd
import apps.reporter as rpt
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

# Input data
fil_num_col_list = ["Age"]
fil_cat_col_list = ["Embarked"]
cat_col_list = ["Sex"]
pd.options.display.float_format = "{:g}".format

# Solution
cat_pipeline = Pipeline([
    ("fil_cat", SimpleImputer(strategy="most_frequent")),
    ("cat", OneHotEncoder(handle_unknown="ignore", sparse_output=False, dtype="int64")),
])
# need to remove original column

preprocessor = ColumnTransformer([
    ("fil_num", SimpleImputer(strategy="median"), fil_num_col_list),
    ("pipe_cat", cat_pipeline, fil_cat_col_list),
    ("cat", OneHotEncoder(handle_unknown="ignore", sparse_output=False, dtype="int64"), cat_col_list),
], remainder="passthrough", verbose_feature_names_out=False)

preprocessor.set_output(transform="pandas")
transformed_data = preprocessor.fit_transform(titanic_dataset)
titanic_dataset_ohe = pd.DataFrame(transformed_data, columns=preprocessor.get_feature_names_out())

data_set = titanic_dataset_ohe
n_columns = data_set.columns.size
n_rows = data_set.index.size

columns_df = pd.DataFrame(data_set.columns, columns=["Columns"])
types_df = pd.DataFrame(data_set.dtypes, columns=["Types"])

col_num_type = data_set.select_dtypes(include=np.number).columns
col_cat_type = data_set.select_dtypes(exclude=np.number).columns

empty_val_by_col = data_set.isnull().sum().to_frame(name='count')
is_empty_val = empty_val_by_col.values.sum() > 0

rp = rpt.Reporter()
rp.add_item("Кількість рядків", str(n_rows))
rp.add_item("Кількість об’єктів у датасеті", str(n_rows))
rp.add_item("Кількість стовпців", str(n_columns))
rp.add_item("Кількість числових ознак", str(col_num_type.size))
rp.add_item("Кількість категоріальних ознак", str(col_cat_type.size))
rp.add_item("Пропущені значення", 'є' if is_empty_val > 0 else 'немає')
rp.print_pd_report("Параметри таблиці з кодуванням")

# Print results
if is_empty_val > 0:
    display(empty_val_by_col.style.set_caption("Кількість пропусків"))
display(types_df.style.set_caption("Типи даних"))
display(data_set)

,Age,Embarked_C,Embarked_Q,Embarked_S,Sex_female,Sex_male,PassengerId,Survived,Pclass,Name,SibSp,Parch,Ticket,Fare,Cabin
0,22,0,0,1,0,1,1,0,3,"Braund, Mr. Owen Harris",1,0,A/5 21171,7.25,NaN
1,38,1,0,0,1,0,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",1,0,PC 17599,71.2833,C85
2,26,0,0,1,1,0,3,1,3,"Heikkinen, Miss. Laina",0,0,STON/O2. 3101282,7.925,NaN
3,35,0,0,1,1,0,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,0,113803,53.1,C123
4,35,0,0,1,0,1,5,0,3,"Allen, Mr. William Henry",0,0,373450,8.05,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,27,0,0,1,0,1,887,0,2,"Montvila, Rev. Juozas",0,0,211536,13,NaN
887,19,0,0,1,1,0,888,1,1,"Graham, Miss. Margaret Edith",0,0,112053,30,B42
888,28,0,0,1,1,0,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",1,2,W./C. 6607,23.45,NaN
889,26,1,0,0,0,1,890,1,1,"Behr, Mr. Karl Howell",0,0,111369,30,C148
890,32,0,1,0,0,1,891,0,3,"Dooley, Mr. Patrick",0,0,370376,7.75,NaN

In [7]:
# Data cleaning

import numpy as np
import pandas as pd
import apps.reporter as rpt
from IPython.core.display import Markdown

# Input data
ages_col_name = "Age"
fares_col_name = "Fare"
sibsp_col_name = "SibSp"
parch_col_name = "Parch"
family_col_name = "Family"
drop_col_list = ["PassengerId", "Name", "Ticket", "Cabin"]

# Solution
titanics = [titanic_dataset, titanic_dataset_ohe]
titles = ["Датасет без кодування:", "Датасет з кодуванням:"]

for idx, titanic in enumerate(titanics):
    titanic.drop(columns=drop_col_list, inplace=True)

    # Корегування даних
    titanic[ages_col_name] = titanic[ages_col_name].round().astype(int)
    titanic[fares_col_name] = titanic[fares_col_name].round(2).astype(float)

    # Заміна даних і очищення
    titanic[family_col_name] = (titanic.apply(lambda df_row: df_row[sibsp_col_name] + df_row[parch_col_name] + 1,
                                              axis=1).astype(int))
    titanic.drop(columns=[sibsp_col_name, parch_col_name], inplace=True)

    data_set = titanic
    n_columns = data_set.columns.size
    n_rows = data_set.index.size

    columns_df = pd.DataFrame(data_set.columns, columns=["Columns"])
    types_df = pd.DataFrame(data_set.dtypes, columns=["Types"])

    col_num_type = data_set.select_dtypes(include=np.number).columns
    col_cat_type = data_set.select_dtypes(exclude=np.number).columns

    empty_val_by_col = data_set.isnull().sum().to_frame(name='count')
    is_empty_val = empty_val_by_col.values.sum() > 0

    rp = rpt.Reporter()
    rp.add_item("Кількість рядків", str(n_rows))
    rp.add_item("Кількість об’єктів у датасеті", str(n_rows))
    rp.add_item("Кількість стовпців", str(n_columns))
    rp.add_item("Кількість числових ознак", str(col_num_type.size))
    rp.add_item("Кількість категоріальних ознак", str(col_cat_type.size))
    rp.add_item("Пропущені значення", 'є' if is_empty_val > 0 else 'немає')

    # Print results
    display(Markdown(f"**{titles[idx]}**"))

    rp.print_pd_report("Параметри таблиці після очищення")

    if is_empty_val > 0:
        display(empty_val_by_col.style.set_caption("Кількість пропусків"))
    display(types_df.style.set_caption("Типи даних"))

    display(data_set)

**Датасет без кодування:**

     Age Embarked  Survived  Pclass     Sex  Fare  Family
0     22        S         0       3    male  7.25       2
1     38        C         1       1  female 71.28       2
2     26        S         1       3  female  7.92       1
3     35        S         1       1  female  53.1       2
4     35        S         0       3    male  8.05       1
..   ...      ...       ...     ...     ...   ...     ...
886   27        S         0       2    male    13       1
887   19        S         1       1  female    30       1
888   28        S         0       3  female 23.45       4
889   26        C         1       1    male    30       1
890   32        Q         0       3    male  7.75       1

[891 rows x 7 columns]

**Датасет з кодуванням:**

,Age,Embarked_C,Embarked_Q,Embarked_S,Sex_female,Sex_male,Survived,Pclass,Fare,Family
0,22,0,0,1,0,1,0,3,7.25,2
1,38,1,0,0,1,0,1,1,71.28,2
2,26,0,0,1,1,0,1,3,7.92,1
3,35,0,0,1,1,0,1,1,53.1,2
4,35,0,0,1,0,1,0,3,8.05,1
...,...,...,...,...,...,...,...,...,...,...
886,27,0,0,1,0,1,0,2,13,1
887,19,0,0,1,1,0,1,1,30,1
888,28,0,0,1,1,0,0,3,23.45,4
889,26,1,0,0,0,1,1,1,30,1
890,32,0,1,0,0,1,0,3,7.75,1